// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThAmCo.Catering.Data;

#nullable disable

namespace ThAmCo.Catering.Data.Migrations
{
    [DbContext(typeof(CateringDbContext))]
    partial class MenusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodBooking", b =>
                {
                    b.Property<int>("FoodBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodBookingId");

                    b.HasIndex("MenuId");

                    b.ToTable("FoodBookings");

                    b.HasData(
                        new
                        {
                            FoodBookingId = 1,
                            ClientReferenceId = 101,
                            MenuId = 1,
                            NumberOfGuests = 10
                        },
                        new
                        {
                            FoodBookingId = 2,
                            ClientReferenceId = 102,
                            MenuId = 2,
                            NumberOfGuests = 5
                        },
                        new
                        {
                            FoodBookingId = 3,
                            ClientReferenceId = 103,
                            MenuId = 3,
                            NumberOfGuests = 8
                        },
                        new
                        {
                            FoodBookingId = 4,
                            ClientReferenceId = 104,
                            MenuId = 4,
                            NumberOfGuests = 12
                        },
                        new
                        {
                            FoodBookingId = 5,
                            ClientReferenceId = 105,
                            MenuId = 5,
                            NumberOfGuests = 7
                        },
                        new
                        {
                            FoodBookingId = 6,
                            ClientReferenceId = 106,
                            MenuId = 6,
                            NumberOfGuests = 9
                        },
                        new
                        {
                            FoodBookingId = 7,
                            ClientReferenceId = 107,
                            MenuId = 7,
                            NumberOfGuests = 6
                        },
                        new
                        {
                            FoodBookingId = 8,
                            ClientReferenceId = 108,
                            MenuId = 8,
                            NumberOfGuests = 11
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("FoodItemId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemId = 1,
                            Description = "Pizza",
                            UnitPrice = 8.99f
                        },
                        new
                        {
                            FoodItemId = 2,
                            Description = "Burger",
                            UnitPrice = 5.99f
                        },
                        new
                        {
                            FoodItemId = 3,
                            Description = "Pasta",
                            UnitPrice = 7.99f
                        },
                        new
                        {
                            FoodItemId = 4,
                            Description = "Tacos",
                            UnitPrice = 6.99f
                        },
                        new
                        {
                            FoodItemId = 5,
                            Description = "Sushi",
                            UnitPrice = 12.99f
                        },
                        new
                        {
                            FoodItemId = 6,
                            Description = "Curry",
                            UnitPrice = 9.99f
                        },
                        new
                        {
                            FoodItemId = 7,
                            Description = "Dim Sum",
                            UnitPrice = 11.99f
                        },
                        new
                        {
                            FoodItemId = 8,
                            Description = "Croissant",
                            UnitPrice = 3.99f
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MenuId");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            MenuName = "Italian Menu"
                        },
                        new
                        {
                            MenuId = 2,
                            MenuName = "American Menu"
                        },
                        new
                        {
                            MenuId = 3,
                            MenuName = "Mexican Menu"
                        },
                        new
                        {
                            MenuId = 4,
                            MenuName = "Indian Menu"
                        },
                        new
                        {
                            MenuId = 5,
                            MenuName = "Chinese Menu"
                        },
                        new
                        {
                            MenuId = 6,
                            MenuName = "Japanese Menu"
                        },
                        new
                        {
                            MenuId = 7,
                            MenuName = "French Menu"
                        },
                        new
                        {
                            MenuId = 8,
                            MenuName = "Greek Menu"
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.MenuFoodItem", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MenuId", "FoodItemId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("MenuFoodItems");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 1
                        },
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 3
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 2
                        },
                        new
                        {
                            MenuId = 3,
                            FoodItemId = 4
                        },
                        new
                        {
                            MenuId = 4,
                            FoodItemId = 6
                        },
                        new
                        {
                            MenuId = 5,
                            FoodItemId = 7
                        },
                        new
                        {
                            MenuId = 6,
                            FoodItemId = 5
                        },
                        new
                        {
                            MenuId = 7,
                            FoodItemId = 8
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodBooking", b =>
                {
                    b.HasOne("ThAmCo.Catering.Data.Menu", "Menu")
                        .WithMany("FoodBooking")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.MenuFoodItem", b =>
                {
                    b.HasOne("ThAmCo.Catering.Data.FoodItem", "FoodItem")
                        .WithMany("MenuFoodItem")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThAmCo.Catering.Data.Menu", "Menu")
                        .WithMany("MenuFoodItem")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodItem", b =>
                {
                    b.Navigation("MenuFoodItem");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.Menu", b =>
                {
                    b.Navigation("FoodBooking");

                    b.Navigation("MenuFoodItem");
                });
#pragma warning restore 612, 618
        }
    }
}
